language: node_js
node_js:
  - "8"
script:
  - yarn build
after_success:
  - curl -T dist/index.html ftp://$FTP_USER:$FTP_PASS@ftp.wishflower.nl/domains/wishflower.nl/public_html/koolhydraatjes/
  - curl -T dist/bundle.js ftp://$FTP_USER:$FTP_PASS@ftp.wishflower.nl/domains/wishflower.nl/public_html/koolhydraatjes/
  - find src/images -type f -exec curl --ftp-create-dirs -T {} ftp://$FTP_USER:$FTP_PASS@ftp.wishflower.nl/domains/wishflower.nl/public_html/koolhydraatjes/images/
