language: node_js
node_js:
  - "8"
script:
  - yarn build
after_success:
  - curl -3 -T dist/index.html ftp://$FTP_USER:$FTP_PASS@ftp.wishflower.nl/public_html/koolhydraatjes \;
  - curl -3 -T dist/bundle.js ftp://$FTP_USER:$FTP_PASS@ftp.wishflower.nl/public_html/koolhydraatjes \;
